export enum AuthMutations {
  API_ACCESS_TOKEN = "API_ACCESS_TOKEN",
  SET_USER_INFO = "SET_USER_INFO",
  GET_USER_SUCCESS = "GET_USER_SUCCESS",
  GET_AUTHENTICATED_USER_SUCCESS = "GET_AUTHENTICATED_USER_SUCCESS",
  SET_FORM_STATE = "SET_FORM_STATE",
}